DROP TABLE IF EXISTS PRODUCTS;
DROP TABLE IF EXISTS USERS;

CREATE TABLE PRODUCTS (
  id INT AUTO_INCREMENT  PRIMARY KEY,
  name VARCHAR(250) NOT NULL,
  type VARCHAR(250) NOT NULL,
  description VARCHAR(250) DEFAULT NULL
);

CREATE TABLE PRODUCT_PRICE (
  product_id INT,
  price DECIMAL NOT NULL
);
ALTER TABLE PRODUCT_PRICE add FOREIGN KEY (product_id) references PRODUCTS(id);

CREATE TABLE PRODUCT_QUANTITY (
  product_id INT,
  quantity INT NOT NULL
);
ALTER TABLE PRODUCT_QUANTITY add FOREIGN KEY (product_id) references PRODUCTS(id);

CREATE TABLE USERS (
  id INT AUTO_INCREMENT  PRIMARY KEY,
  name VARCHAR(250) NOT NULL,
  role VARCHAR(250) NOT NULL
);
